# Welcome to STiM website!

title: Spanish Teachers in Málaga
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
future: true
safe: true

email: info@spanishteachersmalaga.com
phone: +34 619140300
address_1: Plaza Victoria 6, 1ºB
address_2: 29012 - Málaga

github_username: quijotesc
facebook_username: stimalaga
twitter_username: stimalaga

myimage.path: "./assets/img/"


# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  products:
    output: true
  faqs:
    output: true
  
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

